---
- hosts: db
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name:
          - postgresql
          - libpq-dev
          - python3-psycopg2
- hosts: db
  become: yes
  become_user: postgres
  gather_facts: no
  vars:
    - database: ads_microservice_production
    - db_user: ads
    - db_password: 5ca80fa77f9d548a
  tasks:
    - name: ensure database is created
      postgresql_db:
        name: '{{ database }}'
    - name: ensure user has access to database
      postgresql_user:
        db: '{{ database }}'
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        priv: ALL
    - name: ensure user has no extra privileges
      postgresql_user:
        name: '{{ db_user }}'
        role_attr_flags: NOSUPERUSER,NOCREATEDB
    - name: ensure no other user has access to database
      postgresql_privs:
        db: '{{ database }}'
        role: PUBLIC
        type: database
        priv: ALL
        state: absent
